# Generated by Django 3.2.7 on 2021-12-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
