# Generated by Django 3.2.7 on 2022-01-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_car_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='lastMantainTime',
        ),
        migrations.RemoveField(
            model_name='car',
            name='serveTime',
        ),
    ]
